#!/usr/bin/env python3
"""Build the Pinnacle Precision Defence static site.

    python3 tools/generate.py

Writes every page except the homepage from the content modules, patches the
shared header/footer into index.html between its marker comments, and regenerates
sitemap.xml. Output is plain HTML with no runtime dependencies, the published
site does not need Python, Node or any build step on the host.
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import layout                      # noqa: E402
from layout import HEADER, FOOTER, SITE_URL, render   # noqa: E402
from content_capabilities import all_capability_pages  # noqa: E402
from content_sectors import all_sector_pages           # noqa: E402
from content_roadmap import all_roadmap_pages         # noqa: E402
from content_company import all_company_pages          # noqa: E402

# Homepage is hand-authored; everything below is generated.
HOMEPAGE = "index.html"

# Pages listed in sitemap.xml, in priority order. 404 is deliberately excluded.
SITEMAP_PRIORITY = {
    "index.html": "1.0",
    "capabilities/index.html": "0.9",
    "sectors/index.html": "0.9",
    "contact/index.html": "0.8",
    "about/index.html": "0.8",
    "roadmap/index.html": "0.9",
}


def write(path, html):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(html)
    return path


def patch_homepage():
    """Replace the header and footer blocks in the hand-authored homepage."""
    path = os.path.join(ROOT, HOMEPAGE)
    with open(path, encoding="utf-8") as fh:
        html = fh.read()

    header = HEADER.replace("{P}", "")
    footer = FOOTER.replace("{P}", "")

    header_block = (
        "<!-- ====== HEADER (generated by tools/generate.py, do not edit by hand) ====== -->\n"
        + header + "\n<!-- ====== /HEADER ====== -->"
    )
    footer_block = (
        "<!-- ====== FOOTER (generated by tools/generate.py, do not edit by hand) ====== -->\n"
        + footer + "\n<!-- ====== /FOOTER ====== -->"
    )

    # First run replaces the original hand-written blocks; later runs replace the
    # generated ones. The closing-marker branch MUST come first: the </header>
    # branch would otherwise match on a generated file and stop short of the
    # trailing marker, leaving a duplicate behind on every run.
    html, n1 = re.subn(
        r"<!-- =+ HEADER.*?/HEADER =+ -->|<!-- =+ HEADER.*?</header>",
        lambda _: header_block, html, count=1, flags=re.S)
    html, n2 = re.subn(
        r"<!-- =+ FOOTER.*?/FOOTER =+ -->|<!-- =+ FOOTER.*?</footer>",
        lambda _: footer_block, html, count=1, flags=re.S)

    if not (n1 and n2):
        raise SystemExit(
            f"ERROR: could not find HEADER/FOOTER markers in {HOMEPAGE} "
            f"(header={n1}, footer={n2}). Restore the marker comments and re-run.")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html)
    return HOMEPAGE


def write_sitemap(paths):
    urls = []
    for path in paths:
        loc = SITE_URL + "/" + ("" if path == "index.html" else path)
        priority = SITEMAP_PRIORITY.get(path, "0.6")
        urls.append(f"  <url>\n    <loc>{loc}</loc>\n"
                    f"    <priority>{priority}</priority>\n  </url>")
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           + "\n".join(urls) + "\n</urlset>\n")
    return write("sitemap.xml", xml)


def main():
    pages = (all_capability_pages() + all_sector_pages()
             + all_roadmap_pages() + all_company_pages())

    written = [patch_homepage()]
    for path, title, desc, body in pages:
        written.append(write(path, render(path, title, desc, body)))

    sitemap_paths = [HOMEPAGE] + sorted(
        p for p, *_ in pages if p != "404.html"
    )
    write_sitemap(sitemap_paths)

    print(f"Generated {len(written)} pages + sitemap.xml")
    for path in written:
        print("  " + path)

    # Cheap link check: every internal href must resolve to a file on disk.
    broken = []
    for path in written:
        with open(os.path.join(ROOT, path), encoding="utf-8") as fh:
            html = fh.read()
        base = os.path.dirname(os.path.join(ROOT, path))
        for href in re.findall(r'href="([^"#:]+)"', html):
            target = os.path.normpath(os.path.join(base, href.split("#")[0]))
            if not os.path.exists(target):
                broken.append(f"{path} -> {href}")
    if broken:
        print("\nBROKEN INTERNAL LINKS:")
        for item in sorted(set(broken)):
            print("  " + item)
        return 1
    print("\nInternal link check: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
